language: node_js
cache:
  directories:
  - node_modules
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: gai06JYeiQ9qeyF7ueBfXqBgcDIPXL1dcHmNd++5m+4xieMfZnikkC3jOc1w6I00sRhTB6hrsWtyWQedTOQL8g76/FJQkOaZQYZKomtWvkPkB2a0qxSCfmpwxHAkSMmiRvo/v4B7dVjPu5hmE2DyjoNDYvtfqkNAS27j+mdqRQCnJ3o6cWOhpoY8r/OR4arT1y1C5HGlIaP/qQ++XDnq17gZ/u+rmboUEg27kLO/+Yv5rnWoijnDz3Frk3xzDrT/MHSQcDMPJcvT6hnIuX8lot2Nv1wnJcQ5Qajc775wwp/HET5UIuPeTf+xHFy4m4fkvlFC6WFTMODFqMxmMsrLuNl2s9M5xKO0qBvyjNzLRBh9ez5jXHJcOmO5rZH21eCQh0TShxsDqPslsHQ3WqE0xXVrvkJt5DxCBixQwd8Lj+T3mJq6wERulzG5LudD8nhYAP9M0G3q0aBbxEXlvXQCCjnZK5IqliKirkM03DN/NLG0u9wu5tJzIbZjGeCSG8/Ohcp7wAXPzf26dKG+GBp135cNAzTfLsVj5d4ML/t7xs656CFiN5RoaMW2jOMRshSyNNIOQ0Sg6FU7FgXJ2ETaxNcKzfjWWrkprNeOxu1b83BsESbK6FdqpitANTtppRX0cm+Oa24soz3llngYePlYWmI0NrSeYitME/Dk3/v4G/k=
  app: mnitd-server
  on:
    repo: MNITD/editor-server
