language: node_js
cache:
  directories:
  - node_modules
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: DWWaQKQa35dUjVtEk1/CCdn0NF+cjVA7d75DDQTLLAqWhcl6W35upVt9V8CBq6NTxRuWn3Tl2JAjLJpfw1HRBDyg7m7zQLS6DRKqGosGETIROJLIGhMhW5E3zLwLcKIF8jmx998YWChCnOSFfyfcXAVWJOCwh/6VIEJNCYfFMjJxv/zIZteYyCH2avVF2roUxZjGGYwB9WirmUiUcTZMHAoPasGDEtjPs8WnjgKLle4S6pmCt0dcy/cEjZFAZF6FwVe4qr8YmfIzR9XT5qBKDs+xvPS6clxBiC9ACOwpPz9YiZ1keik5eLzRNvZWCRqnGxIJahRVxUJAamscpW/R/LI+dMfFte04TD6pI6CxT+GEUy2wMFozQvRixg/yiK50H8eS3szLWGvbEJLkz5FC/D4nPHoZvAx/vcwP7tvY0V2GQEcL5t8qcWoj9GtsnZ01AzkS5wMts/s3eEPwqCUEGb2TCzoVch9goqstYS7gqqrnaeGfxhRgydjmzXEF5TmgjTR/SO16vVBGz46hexDbp50swdTDSyEuV0S+eu4IyIEI3Fi9Mo/7BKu83SkDzbs9g+mFp+z4TRhoghlch/0oCvO0EzTyfOeMQ883DX90Whq/0uak39KqWJqSmEjx42Dge0RC2mibluqcJhMz5YF+6deu68fP6sAuRktMU2cYhfg=
  app: mnitd-editor
  on:
    repo: MNITD/editor-server
env:
  global:
    secure: WqEJRY1D5CiWGPTlBulwRwbVPiUI1ZXzVLuNENDo2JCGHX6CNC0QTthJ06curxD5xVSLNMmQFtVP6MpaeHI5oZTYBTmVSdf5mKbz26hZNfT/YWCLH5eT+0ux5trzj1PhdhlL//Q69eiYWlAiIuN6erYm07My2M4fANkgPt8eK+zdW55kS1IXHCjQdNla3bAHkIP0ZcnuOXHQXDMhaPfOiPDxopPUqghMFENsUuhG7E3eCjKmDATZdItygK5KUMiWJ2XIX/wNorBtftfOcidfva3iLfeKzcqyPXaW2mTNrImbWJi3xptPPI1ZDiP6X0mzCwwJtFcim6E25lfiE/vtzevqsAz58YTbGEEfZNOIi1ufXR8nbAJ1m8NizrTLQH7saIrWJzRM6PP8hQi6p11lyinCjf0WGiYUAlaFX1EiRAnlv27Gy2E2XZk6d/XIVKKzMvglI3QDHTJjOyvbPds1LdoLxVjcAIpIZS2sg0aGKaO4RrUqO2AcXY7/UhM/gK0rrKhXD35+6cEh/pcfDMLi4WKTiQDO00R3sy6sXB/TjTdg+QNreKX0GrzvMJf9FywOQDHdWf2mzXPHDiqUcQbg666GRR/RUkD65CAfU6WpfON6JlDbel4VQP1PKq1vBM2Quo6tJBT8nqk0Kz6h9aeeKH8fVcSR5v6TurLmAQfUObg=
