### Create new document

POST http://localhost:9000/api/documents
Content-Type: application/json

{"name": "Test", "tree": "{}"}

### Get all documents

GET http://localhost:9000/api/documents

### Get document by id

GET http://localhost:9000/api/documents/5aff8e9000407025583e0e24

### Publish document

POST http://localhost:9000/api/documents/published/5aff8e9000407025583e0e24
Content-Type: application/json

{"name": "Test3", "tree": "{}"}

### Save document

POST http://localhost:9000/api/documents/saved/5aff8e9000407025583e0e24
Content-Type: application/json

{"name": "Test4", "tree": "{}"}

### Register user

POST http://localhost:9000/api/register
Content-Type: application/json

{"login": "Test2", "password": "1234"}


### Login user

POST http://localhost:9000/api/login
Content-Type: application/json

{"login": "Test", "password": "1234"}


###