### Create new document

POST http://localhost:8080/api/documents
Content-Type: application/json

{"name": "Test", "tree": "{}"}

### Get all documents

GET http://localhost:8080/api/documents

### Get document by id

GET http://localhost:8080/api/documents/5aff8e8080407025583e0e24

### Publish document

POST http://localhost:8080/api/documents/published/5aff8e8080407025583e0e24
Content-Type: application/json

{"name": "Test3", "tree": "{}"}

### Save document

POST http://localhost:8080/api/documents/saved/5aff8e8080407025583e0e24
Content-Type: application/json

{"name": "Test4", "tree": "{}"}

###